// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package tokenize

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindUnknown-0]
	_ = x[KindNoun-1]
	_ = x[KindVerb-2]
	_ = x[KindAuxVerb-3]
	_ = x[KindParticle-4]
	_ = x[KindSymbol-5]
	_ = x[KindPrefix-6]
	_ = x[KindAdjective-7]
	_ = x[KindConjunction-8]
	_ = x[KindInterjection-9]
	_ = x[KindAdverb-10]
	_ = x[KindPrenominal-11]
	_ = x[KindFiller-12]
	_ = x[KindOther-13]
}

const _Kind_name = "KindUnknownKindNounKindVerbKindAuxVerbKindParticleKindSymbolKindPrefixKindAdjectiveKindConjunctionKindInterjectionKindAdverbKindPrenominalKindFillerKindOther"

var _Kind_index = [...]uint8{0, 11, 19, 27, 38, 50, 60, 70, 83, 98, 114, 124, 138, 148, 157}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
