const posMap: Record<string, string> = {
  "n": "Noun",
  "n-t": "Noun",
  "n-adv": "Adverbial Noun",
  "n-pref": "Noun (prefix)",
  "n-suf": "Noun (suffix)",
  "n-pr": "Proper Noun",
  "pn": "Pronoun",
  "num": "Numeric",

  "v1": "Verb (一段)",
  "v1-s": "Verb (一段, くれる)",
  "v5aru": "Verb (五段, ある)",
  "v5b": "Verb (五段, ぶ)",
  "v5g": "Verb (五段, ぐ)",
  "v5k": "Verb (五段, く)",
  "v5k-s": "Verb (五段, いく/ゆく)",
  "v5m": "Verb (五段, む)",
  "v5n": "Verb (五段, ぬ)",
  "v5r": "Verb (五段, る)",
  "v5r-i": "Verb (五段, る) - Irregular",
  "v5s": "Verb (五段, す)",
  "v5t": "Verb (五段, つ)",
  "v5u": "Verb (五段, う)",
  "v5u-s": "Verb (五段, う)",
  "v5uru": "Verb (五段, うる) (archaic)",
  "v2a-s": "Verb (二段, う) (archaic)",
  "v2b-k": "Verb (二段, ぶ) (upper class, archaic)",
  "v2b-s": "Verb (二段, ぶ) (lower class, archaic)",
  "v2d-k": "Verb (二段, づ) (upper class, archaic)",
  "v2d-s": "Verb (二段, づ) (lower class, archaic)",
  "v2g-k": "Verb (二段, ぐ) (upper class, archaic)",
  "v2g-s": "Verb (二段, ぐ) (lower class, archaic)",
  "v2h-k": "Verb (二段, ふ) (upper class, archaic)",
  "v2h-s": "Verb (二段, ふ) (lower class, archaic)",
  "v2k-k": "Verb (二段, く) (upper class, archaic)",
  "v2k-s": "Verb (二段, く) (lower class, archaic)",
  "v2m-k": "Verb (二段, む) (upper class, archaic)",
  "v2m-s": "Verb (二段, む) (lower class, archaic)",
  "v2n-s": "Verb (二段, ぬ) (lower class, archaic)",
  "v2r-k": "Verb (二段, る) (upper class, archaic)",
  "v2r-s": "Verb (二段, る) (lower class, archaic)",
  "v2s-s": "Verb (二段, す) (lower class, archaic)",
  "v2t-k": "Verb (二段, つ) (upper class, archaic)",
  "v2t-s": "Verb (二段, つ) (lower class, archaic)",
  "v2w-s": "Verb (二段, う) (lower class, archaic)",
  "v2y-k": "Verb (二段, ゆ) (upper class, archaic)",
  "v2y-s": "Verb (二段, ゆ) (lower class, archaic)",
  "v2z-s": "Verb (二段, ず) (lower class, archaic)",
  "v4b": "Verb (四段, ぶ) (archaic)",
  "v4g": "Verb (四段, ぐ) (archaic)",
  "v4h": "Verb (四段, ふ) (archaic)",
  "v4k": "Verb (四段, く) (archaic)",
  "v4m": "Verb (四段, む) (archaic)",
  "v4n": "Verb (四段, ぬ) (archaic)",
  "v4r": "Verb (四段, る) (archaic)",
  "v4s": "Verb (四段, す) (archaic)",
  "v4t": "Verb (四段, つ) (archaic)",
  "vk": "Verb (くる)",
  "vn": "Verb (ぬ) - Irregular",
  "vr": "Verb (る) - Irregular",
  "vs": "Verb (する)",
  "vs-c": "Verb (する) - Precursor",
  "vs-i": "Verb (する) - Included",
  "vs-s": "Verb (する) - Special",
  "v-unspec": "Verb (unspecified)",
  "vz": "Verb (一段) (zuru variant)",
  "vi": "Verb (intransitive)",
  "vt": "Verb (transitive)",
  "aux-v": "Verb (auxiliary)",
  "aux": "Auxiliary",

  "adj-i": "Adjective",
  "adj-ix": "Adjective",
  "adj-na": "Na-adjective",
  "adj-no": "No-adjective",
  "adj-pn": "Adjective",
  "adj-f": "Adjective",
  "adj-t": "Adjective",
  "adj-kari": "Adjective",
  "adj-ku": "Adjective",
  "adj-shiku": "Adjective",
  "adj-nari": "Adjective",
  "aux-adj": "Auxiliary Adjective",

  "adv": "Adverb",
  "adv-to": "Adverb",
  "prt": "Particle",
  "conj": "Conjunction",
  "int": "Interjection",
  "cop": "Copula",
  "pref": "Prefix",
  "suf": "Suffix",
  "ctr": "Counter",
  "exp": "Expression",
  "id": "Expression",
  "proverb": "Proverb",
  "on-mim": "Onomatopoeia",
  "unc": "Other",
  "oth": "Other",
};

export function formatPos(raw: string): string {
  if (!raw) {
    return "";
  }
  const labels = raw.split(", ").map(l => l.trim());
  const mapped = labels.map(l => posMap[l] ?? l);
  const unique = [...new Set(mapped)];

  return unique.join(", ");
}
